### ISSUE TITLE
Test files

### ISSUE THREAD

**Issue by lambrojos** [eLBati/CBI#1]
Ciao, devo scrivere un parser/writer per CBI in typescript su node.js, stavo pensando di fare un port di questo tuo progetto. Volevo chiederti se per caso potresti aggiungere dei file di esempio da parsare, più che altro per testing.

**Comment by eLBati** [comment]
Ciao @bananajohnny , ho aggiunto il file https://github.com/eLBati/CBI/blob/master/samples/MAV.txt e aggiornato il README
