### ISSUE TITLE
Missing field in LI_IN record?

### ISSUE THREAD

**Issue by lambrojos** [eLBati/CBI#2]
I noticed that the LI_IN record definition 

```
LI_IN = [
    (1, 1, 'filler1'),
    (2, 3, 'tipo_record'),
    (4, 10, 'numero_progressivo'),
    (11, 20, 'numero_disposizione'),
    (21, 74, 'filler2'),
    (75, 86, 'codice_identificativo_univoco'),
    (87, 91, 'importo'),
    (92, 97, 'valuta_di_addebito'),
    (98, 109, 'riferimento'),
    (110, 115, 'data_effettiva_di_pagamento'),
    ]
```

is just 115 chars long, is that right?  In the example file (MAV.txt),  the lines corresponding to this record type are 120 chars long, it seems that there must be an error in test file or in the record definition.

**Comment by eLBati** [comment]
@lambrojos I think you are right. According to CBI-MAV-001 6.01:
87-120 - - filler N blank

See PR https://github.com/eLBati/CBI/pull/3 should fix this

Thanks
